### PR TITLE
Add product id to pac_bio_product_metrics table.

### PR DESCRIPTION
**Pull request by mksanger**

### CODE REVIEW

**Comment by mgcam** [comment]
Since the pac_bio_run table is maintained by the LIMS team, it might be unwise to add a column to this table.

**Comment by mksanger** [comment]
> Since the pac_bio_run table is maintained by the LIMS team, it might be unwise to add a column to this table.

There is no change to pac_bio_run, only pac_bio_product_metrics.

**Comment by mgcam** [comment]
> > Since the pac_bio_run table is maintained by the LIMS team, it might be unwise to add a column to this table.
> 
> There is no change to pac_bio_run, only pac_bio_product_metrics.

Indeed, apologies

**Comment by mgcam** [comment]
Add a unique key to the new column?

**Pull request merged**
